// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmY-dKTEYRo7LaGQY247IRx4ioRsLQym0',
    appId: '1:636016915209:web:31e2c5ef146bafcb18d9d8',
    messagingSenderId: '636016915209',
    projectId: 'judica-cc7c2',
    authDomain: 'judica-cc7c2.firebaseapp.com',
    storageBucket: 'judica-cc7c2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5vx2vUEMXciCEq9bgMKj_H42Jzz8TH1w',
    appId: '1:636016915209:android:a119dc49b077eaac18d9d8',
    messagingSenderId: '636016915209',
    projectId: 'judica-cc7c2',
    storageBucket: 'judica-cc7c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjVP9lh04NrEp7-YLEX3Nhm5dsriHFVKQ',
    appId: '1:636016915209:ios:5ebc5260800c43dc18d9d8',
    messagingSenderId: '636016915209',
    projectId: 'judica-cc7c2',
    storageBucket: 'judica-cc7c2.firebasestorage.app',
    iosBundleId: 'com.example.judica',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjVP9lh04NrEp7-YLEX3Nhm5dsriHFVKQ',
    appId: '1:636016915209:ios:5ebc5260800c43dc18d9d8',
    messagingSenderId: '636016915209',
    projectId: 'judica-cc7c2',
    storageBucket: 'judica-cc7c2.firebasestorage.app',
    iosBundleId: 'com.example.judica',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmY-dKTEYRo7LaGQY247IRx4ioRsLQym0',
    appId: '1:636016915209:web:c10c6c9d2eca7f0818d9d8',
    messagingSenderId: '636016915209',
    projectId: 'judica-cc7c2',
    authDomain: 'judica-cc7c2.firebaseapp.com',
    storageBucket: 'judica-cc7c2.firebasestorage.app',
  );

}